### PR TITLE
Search venue

### PR DESCRIPTION
**Pull request by forever-ram**
1) Fix for show venues as per occupency.
2) Fix for Price scale and make it upto $20000

### CODE REVIEW

**Comment by nearbycoder** [comment]
This commit has already been merged into master.

**Comment by forever-ram** [comment]
is our master and sprint_branch_10_5_16 branch have same code?

**Comment by nearbycoder** [comment]
@forever-ram yes. The way we deploy at MBM is we PR everything into the Sprint branch and then when we push to Production that gets merged into Master for Deploy.

**Comment by forever-ram** [comment]
@nearbycoder 
Thanks for notify this.

Yes, I know this follow, but Unfortunately I've made PR directly for Master, Sprint branch don't have that code.

As we got issue that searching not work as expected, that's why I made this PR, and asking for we have same code or not.

**Pull request closed without merging**
