### PR TITLE
Responsive fixes 12 12 16

### PR DESCRIPTION
**Pull request by madebymunsters**
@nearbycoder Take a look at this and let me know your thoughts. I've made sure all the consumer-facing pages are taken care of, and everything works on multiple sizes from my side thus far.

### CODE REVIEW

**Comment by nearbycoder** [comment]
Looks like there is an issue with tablet landscape on the search page

screenshot at jan 03 08-39-42

**Comment by nearbycoder** [comment]
Form is a little wonky on ipad and iphone for need-a-venue
screenshot at jan 03 08-43-21

**Comment by nearbycoder** [comment]
Font heart icon is centered on mobile

screenshot at jan 03 08-47-31

**Comment by nearbycoder** [comment]
@joeykirk besides the few issues mentioned above everything else looks really good!

**Comment by madebymunsters** [comment]
@nearbycoder Fixed the responsive issues. Let me know if you see anything missing in here. Thanks!

**Comment by nearbycoder** [comment]
looks good and works well. Did a slight fix on the padding around the container wrapper.

**Pull request merged**
